DOMAIN="tryfi"
COMPONENTS=["light"]
DEFAULT_POLLING_RATE="10"
CONF_POLLING_RATE=30
CONF_USERNAME="username"
CONF_PASSWORD="password"
SENSOR_STATS_BY_TIME=[
    "DAILY",
    "WEEKLY",
    "MONTHLY"
]
SENSOR_STATS_BY_TYPE=[
    "STEPS",
    "DISTANCE" #FUTURE COULD INCLUDE STEP GOAL
]